name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build and Test AWS CDK Typescript Stack
    runs-on: windows-latest
    steps:
      - name: Initiated By User
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Change Directory (if `package.json` is in a subfolder)
        run: ./cdk-test  # Change this to the folder containing package.json

      
      - name: Install Node
        uses: actions/setup-node@v3
      
      - name: Install Dependencies
        run: npm install

      - name: Build CDK Stack
        run: npm run build
      
      - name: Run Unit Tests
        run: npm run test
      
      - name: Diff AWS CDK Stack
        run: "npx cdk diff MyFirstCdkStack --ci --require-approval never --no-asset-metadata"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"